"""Example 03 – Per-section LLM overrides.

Demonstrates:
- Using a cheap/fast model for data-gathering sections
- Switching to a more capable model for sections requiring nuanced judgement
- Combining per-section LLM with auto-transitions and strict validation

Cost strategy in this example:
  - "intake"   – gpt-4o-mini  (structured data collection, no reasoning needed)
  - "analyse"  – gpt-4o       (requires synthesis and nuanced advice)
  - "report"   – gpt-4o-mini  (structured output generation)
"""

import os

from langchain_openai import ChatOpenAI
from langchain.agents import create_react_agent
from langchain_core.tools import tool

from section_flow import SectionFlowMiddleware, SectionConfig


# ---------------------------------------------------------------------------
# Models
# ---------------------------------------------------------------------------

fast_model = ChatOpenAI(model="gpt-4o-mini", api_key=os.environ["OPENAI_API_KEY"])
smart_model = ChatOpenAI(model="gpt-4o", api_key=os.environ["OPENAI_API_KEY"])


# ---------------------------------------------------------------------------
# Tools
# ---------------------------------------------------------------------------

@tool
def record_symptoms(symptoms: list[str], duration_days: int) -> str:
    """Record the patient's symptoms and how long they've had them."""
    return f"Recorded {len(symptoms)} symptom(s) over {duration_days} day(s)."


@tool
def lookup_medical_guidelines(condition: str) -> str:
    """Look up current clinical guidelines for a condition."""
    # Stub – connect to a real guidelines API in production
    return f"Guidelines for '{condition}': Rest, hydration, and monitor temperature. Seek care if >72 h."


@tool
def generate_summary_report(patient_name: str, findings: str) -> str:
    """Generate a structured summary report for the patient."""
    return (
        f"PATIENT SUMMARY – {patient_name}\n"
        f"{'=' * 40}\n"
        f"{findings}\n"
        f"{'=' * 40}\n"
        "Generated by Health Assistant v0.1"
    )


# ---------------------------------------------------------------------------
# Section definitions
# ---------------------------------------------------------------------------

sections = {
    "intake": SectionConfig(
        name="intake",
        prompt=(
            "You are collecting patient information.\n"
            "Ask for: (1) patient name, (2) list of symptoms, (3) duration in days.\n"
            "Call record_symptoms once you have the information, then transition to 'analyse'."
        ),
        tools=[record_symptoms],
        allowed_transitions=["analyse"],
        llm=fast_model,  # cheap model is sufficient for structured intake
    ),
    "analyse": SectionConfig(
        name="analyse",
        prompt=(
            "You are a clinical advisor reviewing the collected symptoms.\n"
            "Look up relevant guidelines, synthesise the findings, and prepare a clear "
            "recommendation for the patient.\n"
            "When your analysis is complete, transition to 'report'."
        ),
        tools=[lookup_medical_guidelines],
        allowed_transitions=["report"],
        llm=smart_model,  # upgrade to capable model for nuanced medical reasoning
        required_state_fields={},
    ),
    "report": SectionConfig(
        name="report",
        prompt=(
            "You are generating the final patient report.\n"
            "Summarise the consultation in plain language and call generate_summary_report.\n"
            "Keep the tone warm and the language clear for a non-medical audience."
        ),
        tools=[generate_summary_report],
        allowed_transitions=[],
        llm=fast_model,  # back to cheap model for structured output
    ),
}

# ---------------------------------------------------------------------------
# Agent setup
# ---------------------------------------------------------------------------

middleware = SectionFlowMiddleware(
    sections=sections,
    initial_section="intake",
    fallback_section="intake",
)

# The graph-level model acts as the default; per-section llm overrides it.
agent = create_react_agent(
    model=fast_model,
    system_prompt=(
        "You are a virtual health assistant. Always follow your current section's "
        "instructions and be concise and empathetic."
    ),
    middleware=[middleware],
)

# ---------------------------------------------------------------------------
# Run
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    result = agent.invoke(
        {
            "messages": [
                {
                    "role": "user",
                    "content": "Hello, I've had a headache and mild fever for 3 days.",
                }
            ]
        }
    )
    for msg in result["messages"]:
        print(f"[{msg.type}] {msg.content}\n")
